apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
      name: jupyterport
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: terminalport
  selector:
    app: jupyter-app
